// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "overview": [
    "index"
  ],
  "csharp": [
    {
      "type": "doc",
      "id": "csharp/index",
      "label": "Introduction"
    },
    {
      "type": "doc",
      "id": "csharp/license",
      "label": "License"
    },
    {
      "type": "doc",
      "id": "csharp/requirements",
      "label": "Requirements"
    },
    {
      "type": "doc",
      "id": "csharp/installation",
      "label": "Installing into a project"
    },
    {
      "type": "doc",
      "id": "csharp/usage",
      "label": "Basic usage"
    },
    {
      "type": "doc",
      "id": "csharp/gallery",
      "label": "Running the gallery"
    },
    {
      "type": "category",
      "label": "Walkthroughs",
      "items": [
        "how-to/window-and-title-bar",
        "how-to/theme-and-accent",
        "how-to/inputs-and-data",
        "how-to/navigation-and-tabs",
        "how-to/dialogs-and-feedback",
        "how-to/controls-from-csharp"
      ]
    },
    {
      "type": "ref",
      "id": "controls",
      "label": "Control catalog"
    },
    {
      "type": "category",
      "label": "C# API reference",
      "items": [
        {
          "type": "category",
          "label": "Fluence.Wpf",
          "items": [
            {
              "type": "autogenerated",
              "dirName": "api/Fluence.Wpf"
            }
          ],
          "link": {
            "type": "doc",
            "id": "api/Fluence.Wpf/index"
          }
        },
        {
          "type": "category",
          "label": "Fluence.Wpf.Controls",
          "items": [
            {
              "type": "autogenerated",
              "dirName": "api/Fluence.Wpf.Controls"
            }
          ],
          "link": {
            "type": "doc",
            "id": "api/Fluence.Wpf.Controls/index"
          }
        },
        {
          "type": "category",
          "label": "Fluence.Wpf.Markup",
          "items": [
            {
              "type": "autogenerated",
              "dirName": "api/Fluence.Wpf.Markup"
            }
          ],
          "link": {
            "type": "doc",
            "id": "api/Fluence.Wpf.Markup/index"
          }
        },
        {
          "type": "category",
          "label": "Fluence.Wpf.Automation",
          "items": [
            {
              "type": "autogenerated",
              "dirName": "api/Fluence.Wpf.Automation"
            }
          ],
          "link": {
            "type": "doc",
            "id": "api/Fluence.Wpf.Automation/index"
          }
        }
      ],
      "link": {
        "type": "doc",
        "id": "api/index"
      }
    },
    {
      "type": "category",
      "label": "Architecture",
      "items": [
        "explanation/architecture",
        "winui-parity",
        "theming",
        "reference/accessibility"
      ]
    },
    {
      "type": "doc",
      "id": "csharp/contributing",
      "label": "Contributing"
    }
  ],
  "controls": [
    {
      "type": "doc",
      "id": "controls",
      "label": "Control catalog"
    },
    {
      "type": "category",
      "label": "Windows and layout",
      "items": [
        "controls/fluence-window",
        "controls/title-bar",
        "controls/border",
        "controls/card",
        "controls/expander",
        "controls/dock-panel",
        "controls/stack-panel",
        "controls/separator",
        "controls/scroll-bar-extensions",
        "controls/smooth-scroll-viewer"
      ]
    },
    {
      "type": "category",
      "label": "Buttons and actions",
      "items": [
        "controls/button",
        "controls/app-bar-button",
        "controls/hyperlink-button",
        "controls/repeat-button",
        "controls/drop-down-button",
        "controls/split-button",
        "controls/toggle-button",
        "controls/toggle-split-button"
      ]
    },
    {
      "type": "category",
      "label": "Inputs and selection",
      "items": [
        "controls/auto-suggest-box",
        "controls/check-box",
        "controls/color-picker",
        "controls/combo-box",
        "controls/date-picker",
        "controls/number-box",
        "controls/password-box-extensions",
        "controls/radio-button",
        "controls/rating-control",
        "controls/slider",
        "controls/text-box",
        "controls/time-picker",
        "controls/toggle-switch"
      ]
    },
    {
      "type": "category",
      "label": "Navigation and collections",
      "items": [
        "controls/breadcrumb-bar",
        "controls/breadcrumb-bar-item",
        "controls/navigation-view",
        "controls/navigation-view-item",
        "controls/navigation-view-item-header",
        "controls/navigation-view-item-separator",
        "controls/pips-pager",
        "controls/selector-bar",
        "controls/selector-bar-item",
        "controls/slide-navigation-presenter",
        "controls/tab-view",
        "controls/tab-view-item",
        "controls/list-box",
        "controls/list-box-item",
        "controls/list-view",
        "controls/tree-view",
        "controls/tree-view-item"
      ]
    },
    {
      "type": "category",
      "label": "Dialogs, menus, and feedback",
      "items": [
        "controls/content-dialog",
        "controls/command-bar-flyout",
        "controls/command-bar-flyout-presenter",
        "controls/context-menu",
        "controls/flyout",
        "controls/flyout-base",
        "controls/flyout-presenter",
        "controls/menu",
        "controls/menu-item",
        "controls/teaching-tip",
        "controls/tool-tip",
        "controls/info-bar",
        "controls/info-badge",
        "controls/progress-bar",
        "controls/progress-ring"
      ]
    },
    {
      "type": "category",
      "label": "Text, icons, and images",
      "items": [
        "controls/text-block",
        "controls/text-block-extensions",
        "controls/font-icon",
        "controls/image",
        "controls/person-picture"
      ]
    },
    {
      "type": "ref",
      "id": "csharp/usage",
      "label": "C# basic usage"
    },
    {
      "type": "ref",
      "id": "powershell/controls",
      "label": "Controls in PowerShell"
    }
  ],
  "powershell": [
    {
      "type": "doc",
      "id": "powershell/README",
      "label": "Introduction"
    },
    {
      "type": "doc",
      "id": "powershell/license",
      "label": "License"
    },
    {
      "type": "doc",
      "id": "powershell/requirements",
      "label": "Requirements"
    },
    {
      "type": "doc",
      "id": "powershell/installation",
      "label": "Installing the module"
    },
    {
      "type": "doc",
      "id": "powershell/usage",
      "label": "Basic usage"
    },
    {
      "type": "doc",
      "id": "powershell/controls",
      "label": "Controls and dialogs"
    },
    {
      "type": "category",
      "label": "Walkthroughs",
      "items": [
        "powershell/how-to/dialogs",
        "powershell/how-to/forms-and-validation",
        "powershell/how-to/progress",
        "powershell/how-to/windows-from-xaml",
        "powershell/how-to/theming-at-runtime",
        "powershell/how-to/use-in-existing-host"
      ]
    },
    {
      "type": "category",
      "label": "Functions reference",
      "items": [
        {
          "type": "category",
          "label": "Functions",
          "items": [
            {
              "type": "autogenerated",
              "dirName": "powershell/reference"
            }
          ]
        },
      ],
      "link": {
        "type": "doc",
        "id": "powershell/reference/README"
      }
    },
    {
      "type": "doc",
      "id": "powershell/explanation",
      "label": "Module architecture"
    },
    {
      "type": "doc",
      "id": "powershell/contributing",
      "label": "Contributing"
    }
  ]
};

export default sidebars;
